### ISSUE TITLE
Requirements file missing

### ISSUE THREAD

**Issue by christensen143** [gregoryjordanm/awsrightsizer#22] opened 2018-10-22 01:44 UTC
**Describe the bug**
No requirements file.

**To Reproduce**
1. Clone repo
2. Follow directions for installing from source

**Expected behavior**
When running pip install -r requirements the required modules are installed.

**Screenshots**

**Desktop/Server (please complete the following information):**
- OS - Ubuntu 18.04 Desktop
- Python 3.6.6

**Additional context**

**Comment by j4ng5y** [comment] 2018-10-22 14:10
duplicate of #23

**Closed as completed by j4ng5y** 2018-10-22 14:10 UTC
Labels: duplicate
